### ISSUE TITLE
No longer detecting distro in AstroNvim v4

### ISSUE THREAD

**Issue by Hacksore** [creativenull/dotfyle-metadata.nvim#12]
they made some [breaking changes and released 4.x](https://docs.astronvim.com/configuration/v4_migration/) and now they use new libs and our old check fails.

So not sure we want to capture the version that they are using or we could just add checks for this to make to make it work again.

```
loaded, _ = pcall(require, "astrocore");
```

Thoughts? I'm happy to send a PR for this but wanna start the convo first.

**Comment by creativenull** [comment]
I can leave it to you to make that PR!

Just want to make sure we can still keep the check for astronvim v3 too, in case ppl are still using it.
