### ISSUE TITLE
Show keymaps only for normal, insert and visual mode

### ISSUE THREAD

**Issue by creativenull** [creativenull/dotfyle-metadata.nvim#2]
No need to show all keymap modes, most of them are exclusive to plugins.

Another thing would be to only show user generated keymaps and not just everything.

**Comment by RoryNesbitt** [comment]
What modes would you include?
n, x, v (cause people assume this does what x does), i, t?

**Comment by creativenull** [comment]
Expanded to `t` and `x` mappings
