### ISSUE TITLE
There is an error in the distribution detect

### ISSUE THREAD

**Issue by mimikun** [creativenull/dotfyle-metadata.nvim#7]
I'm not using a distribution, but it says `AstroNvim`.

my config: https://github.com/mimikun/dotfiles/tree/master/dot_config/nvim
my dotfyle.json: https://github.com/mimikun/dotfiles/blob/master/dot_config/nvim/dotfyle.json

**Comment by creativenull** [comment]
I've pushed a fix, give it a try and let me know if that helped.

**Comment by Hacksore** [comment]
i had nothing to do with #6 
![homer-homer-simpson](https://github.com/creativenull/dotfyle-metadata.nvim/assets/996134/c6dac048-d939-4299-9afd-2c75d8c9faee)

**Comment by mimikun** [comment]
I've confirmed that the https://github.com/creativenull/dotfyle-metadata.nvim/commit/cccb96d9305eb261611168ae93cc9a4206a1786d commit fixes this issue.
Thank you!
